output "target_group_arn" {
  description = "Arn of the load balancer target group that should forward the traffic to the EC2 instances"
  value       = aws_lb_target_group.app.arn
}

output "security_group_id" {
  description = "Only the security group of the load balancer is allowed to send traffic to EC2 instances"
  value       = aws_security_group.public.id
}

output "dns_name" {
  description = "DNS name of the load balancer generated by AWS."
  value       = aws_lb.entry_point.dns_name
}

output "zone_id" {
  description = "DNS zone ID of the load balancer generated by AWS."
  value       = aws_lb.entry_point.zone_id
}
