output "cloudfront_dns_name" {
  description = "The default DNS name generated by AWS when creating the cloudfront distribution."
  value       = aws_cloudfront_distribution.frontend.domain_name
}

output "cloudfront_zone_id" {
  description = "The default DNS zone ID generated by AWS when creating cloudfront distribution."
  value       = aws_cloudfront_distribution.frontend.hosted_zone_id
}
