variable "common" {
  description = "Common properties reused in multiple modules."
  type = object({
    project_name = string
  })
  validation {
    condition     = length(var.common.project_name) < 16
    error_message = "Project name needs to be shorter than 16 characters, since it will be used as a prefix for the name tag."
  }
}

variable "domain_name" {
  description = "Your custom domain name (e.g. example.com)."
  type        = string
}

variable "service_dns_prefix" {
  description = "The prefix to your domain name that the service you want to register should use (e.g. backend.) - prefix should end with a dot."
  type        = string
  validation {
    condition     = length(regex("^.*\\.", var.service_dns_prefix)) > 0
    error_message = "DNS prefix needs to end with a dot."
  }
}

variable "service_default_dns_name" {
  description = "The default DNS name of the service generated by AWS."
  type        = string
}

variable "service_default_zone_id" {
  description = "The default DNS zone ID of the service generated by AWS."
  type        = string
}
